### ISSUE TITLE
downloads amd64 only binary

### ISSUE THREAD

**Issue by jelmer** [fiaasco/borgbackup#15]
The binary that's being downloaded is specific to amd64, and that means that this role doesn't work for e.g. arm hosts. It would be great if borgbackup could be installed from e.g. apt.

**Comment by Notmarrco** [comment]
If I'm not mistaken, you can add something like this in your playbook's vars or in your host_vars/ : (example for linux 32b version 1.1.9)

```
borgbackup_download_url: "https://github.com/borgbackup/borg/releases/download/{{borgbackup_version }}/borg-linux32"
borgbackup_checksum:"sha256:4d47902c89b1c0233a712296c913b8218a1890629701f4bf4dedf1127477629e"
```

**Comment by noplanman** [comment]
@stroobl This issue can be closed, as setting the `download_url` and `checksum` parameters give all the freedom :+1:
