### ISSUE TITLE
Versioning releases for Ansible Galaxy

### ISSUE THREAD

**Issue by TravisWhitehead** [fiaasco/borgbackup#17]
It may be prudent to tag releases following the [semantic versioning standard](https://semver.org/).

Ansible Galaxy will automatically look for tags following the format and import them:
https://galaxy.ansible.com/docs/contributing/version.html

When semver is followed correctly, this is very useful for downstream users, as it allows us to pin versions and consider which releases may be breaking backwards compatibility or not. Thanks!

**Comment by Notmarrco** [comment]
It seems that fiaasco.borgbackup is not even in ansible galaxy any more. :-(

**Comment by TravisWhitehead** [comment]
We're maintaining a fork over at https://github.com/tag1consulting/ansible-role-borgbackup, you can find it as `tag1consulting.borgbackup` on Ansible Galaxy.

**Comment by stroobl** [comment]
All, sorry for the extreme late reply. This project is not dead, we just had some issues while removing the camelcase from our github organisation name which caused Galaxy to break. That in combination with the fact that apparently I don't get notified by e-mail about new bugs and PRs here. I added a first releases and I'll take a look on the other open requests and discuss with @dverhelst  on how to proceed. It's probably interesting to check what @TravisWhitehead already has in his fork too. :)

**Comment by TravisWhitehead** [comment]
Happy to hear it!

We mostly forked over wanting to use the package manager instead of downloading files (https://github.com/fiaasco/borgbackup/pull/18), but it would be great to move back to upstream (here) if ya'll are interested in offering that feature.

**Comment by stroobl** [comment]
Ok, I noticed you have some open issues in your forked repo for tasks @dverhelst started to work on. We have to improve the molecule tests and linting, since this is our oldest and only project with a low Galaxy score. :)
