### ISSUE TITLE
Wrong SSH User in Server Task

### ISSUE THREAD

**Issue by n1ete** [FiaasCo/borgbackup#8]
Using your Borg script and just at the beginning to explore ansible and need some help with an error i got:

at the server task for user creation i got the following error:
`task path: /roles/borgbackup/tasks/borg-server.yml:2
failed: [borg] (item={'fqdn': 'BORGBACKUPSERVERIP', 'user': 'borgbackup', 'type': 'normal', 'home': '/borgrepo/', 'pool': 'repos', 'options': ''}) => {"item": {"fqdn": "BORGBACKUPSERVERIP", "home": "/borgrepo/", "options": "", "pool": "repos", "type": "normal", "user": "borgbackup"}, "msg": "Failed to connect to the host via ssh: user@BORGBACKUPSERVERIP: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}
fatal: [borg]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_ignore_errors": null, "_ansible_item_result": true, "item": {"fqdn": "BORGBACKUPSERVERIP", "home": "/borgrepo/", "options": "", "pool": "repos", "type": "normal", "user": "borgbackup"}, "msg": "Failed to connect to the host via ssh: user@BORGBACKUPSERVERIP: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}]}
	to retry, use: --limit @/borgbackup.retry
`
seems like it connects with my actually username from localmachine instead of the defined  ssh_user in my inventory.
at the other tasks where ok, why is anther ssh login anyways needed?

can help me pointing me into the right direction to fix this?
i also added version 1.1.5 but was not able to find the borg sha256 checksumms?
thanks in advance for publishing this script and your time and effort ;)

**Comment by stroobl** [comment]
The deployment with Ansible will always use your local user to connect to the server and the client. This is standard Ansible behaviour, you have to make sure you run with a user with access and sudo permissions. The ssh user configured in the role (borgbackup_client_user) is the user used to connect from the client to the server. It will be created by the role.

If you update the version, you should calculate the sha256 checksum (use sha256sum <file> on linux) and also update that in the variables.
